name: currency_converter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  get_storage: ^2.0.3
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/